# Generated by Django 5.2.3 on 2025-07-02 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database')], default='backend', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('backend_technology', models.ForeignKey(blank=True, limit_choices_to={'type': 'backend'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backend_templates', to='core.technology')),
                ('frontend_technology', models.ForeignKey(blank=True, limit_choices_to={'type': 'frontend'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontend_templates', to='core.technology')),
            ],
        ),
    ]
